<a href="https://colab.research.google.com/github/httpMatheus-dev/inteligencia-artificial-umc/blob/main/Exerc%C3%ADcios_DataScience_MatheusGabriel_6B_Noturno.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercícios de NumPy, SciPy, Pandas e Matplotlib — Lista 2

**Aluno:** Matheus Gabriel Alves da Silva | **RGM:** 11241100109  
**Turma:** 6B — Noturno | **Disciplina:** Inteligência Artificial — UMC  
**Professor:** Dr. Fabiano B. Menegidio


---
# 1. NumPy

In [142]:
import numpy as np

In [143]:
# 1. Crie um array unidimensional de 50 elementos contendo numeros inteiros aleatorios entre 10 e 100.

listaArray = np.random.randint(10, 101, 50)

print(listaArray)


[55 69 15 40 12 96 55 68 50 96 19 36 88 45 65 64 50 61 26 34 69 95 99 99
 58 20 18 45 74 15 31 52 56 83 44 52 81 59 53 48 71 15 61 13 43 78 24 11
 68 45]


In [144]:
# 2. Gere uma matriz 4x4 com numeros inteiros de 1 a 16 e extraia a ultima linha.

matriz_4x4 = np.arange(1, 17).reshape(4, 4)
ultima_linha = matriz_4x4[-1]

print(matriz_4x4)
print()
print(ultima_linha)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[13 14 15 16]


In [145]:
# 3. Crie um array de zeros com comprimento 15 e substitua os valores da 5ª a 10ª posicao por 1.

array_zerado = np.zeros(15)
print(f'Array criado e zerado: {array_zerado}')

array_zerado[4:10] = 1
print(f'Array com o 1: {array_zerado}')


Array criado e zerado: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array com o 1: [0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


In [146]:
# 4. Gere um array de 100 numeros inteiros aleatorios e encontre a mediana e a moda dos valores.

arrayInteiros = np.random.randint(1, 80, 100)
print(arrayInteiros)
mediana = np.median(arrayInteiros)
print(f'Mediana: {mediana}')
moda = np.argmax(np.bincount(arrayInteiros))
print(f'Moda: {moda}')

[46  4 27 50  4 11 31 19  9 54 51 76 51 77 74 39 47 73 40 20  1 21 72 37
 17 11 56 43 56  1 22 48 53 51 51 23 53 70 48 59 63 78 25 38 38 33 39 58
 47  6 14 16 22 34 37 46 61 37 14 72 51 50 38 32 69 54 75 66 60 59 30 36
 71 50 68 33 31 27 73 54 12 66 52 65 14 59 25 11 32 66 38 34 22 67 12  5
 67 17 20 34]
Mediana: 39.5
Moda: 51


In [147]:
# 5. Crie um array de 20 elementos contendo numeros entre 1 e 100 e substitua todos os valores multiplos de 3 por -3.
arrayelementos = np.random.randint(1, 101, 20)
print(f'Array antes de mudar: {arrayelementos}')
arrayelementos[arrayelementos % 3 == 0] = -3
print()
print(f'Array apos mudar: {arrayelementos}')



Array antes de mudar: [95 29  3 54 29 41 85 99 20 58 89 51 63 15 29 99 30 68 89 19]

Array apos mudar: [95 29 -3 -3 29 41 85 -3 20 58 89 -3 -3 -3 29 -3 -3 68 89 19]


In [148]:
# 6. Gere uma matriz 5x5 de numeros aleatorios entre 0 e 1 e encontre a soma de cada coluna.
matriz_5x5 = np.random.rand(5,5)
print(f'Matriz:\n{matriz_5x5}')

somaColunas = matriz_5x5.sum(axis=0)
print(f'Soma das colunas: {somaColunas}')

Matriz:
[[0.2774233  0.81397898 0.59941226 0.39837574 0.28753213]
 [0.0105974  0.92870887 0.9707378  0.38574362 0.96111611]
 [0.44398397 0.17358377 0.53178189 0.94856979 0.85926249]
 [0.51421706 0.39637895 0.31936886 0.05158228 0.54454657]
 [0.12278282 0.22019183 0.71381177 0.71452238 0.65871083]]
Soma das colunas: [1.36900454 2.5328424  3.13511257 2.49879381 3.31116812]


In [149]:
# 7. Crie dois arrays de numeros aleatorios e encontre a correlacao entre eles
arrayePrimario = np.random.randint(1, 30, 20)
arrayeSecundario = np.random.randint(1, 30, 20)
correlacao = np.corrcoef(arrayePrimario, arrayeSecundario) [0, 1]

print(f'Primeiro: {arrayePrimario}')
print(f'Secundario: {arrayeSecundario}')
print(f'Correlacao: {correlacao}')

Primeiro: [25 28 11 25  5 15 18  5 13  3 23 21  2 25 23  2  5  6 22 10]
Secundario: [ 2  3 19  1 13 16  1  1 17  8 19  8 16 13  6 16 16 22 20 20]
Correlacao: -0.37211310390061275


In [150]:
# 8. Gere uma matriz 3x3 com numeros inteiros aleatorios e eleve todos os seus elementos ao quadrado.

matriz_3x3 = np.random.randint(1, 10, (3, 3))
print(f'Matriz:\n{matriz_3x3}')
elevados = matriz_3x3 ** 2
print(f'Quadrados:\n{elevados}')


Matriz:
[[5 1 1]
 [7 9 2]
 [7 4 1]]
Quadrados:
[[25  1  1]
 [49 81  4]
 [49 16  1]]


In [151]:
# 9. Crie um array com 10 numeros aleatorios e normalize seus valores entre 0 e 1
array_10 = np.random.randint(1, 20, 10)
print(array_10)

normalizado = (array_10 - array_10.min()) / (array_10.max() - array_10.min())
print(normalizado)

print(normalizado.min())   # tem que dar 0.0
print(normalizado.max())   # tem que dar 1.0

[ 5  4  9  7  4 13 19  9 18 15]
[0.06666667 0.         0.33333333 0.2        0.         0.6
 1.         0.33333333 0.93333333 0.73333333]
0.0
1.0


In [152]:
# 10. Crie uma matriz identidade 6x6 e substitua a diagonal principal por valores crescentes de 1 a 6.
matriz_6x6 = np.eye(6)
print(matriz_6x6)
np.fill_diagonal(matriz_6x6, [1,2,3,4,5,6])
print(matriz_6x6)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 6.]]


In [153]:
# 11. Gere um array de 100 números inteiros e encontre o valor que mais se repete no array.
array_100 = np.random.randint(1, 100, 100)
print((f'array original:\n{array_100}'))
repete = np.argmax(np.bincount(array_100))
print(f'O numero que mais se repete: {repete}')

# bincount conta quantas vezes cada número aparece;
# o índice do resultado é o próprio número, então argmax devolve a moda

array original:
[10 37 84  2 16 20 11 62 14 61 49 11 75 82 10 55 20 38  8 12 20 11 56  9
 36  7 57 94 30 69 44 94 89 34 37 66 78 58  9 93 55 91 53 56 57 95  4  9
 55  1 70 28 41 10  7  7 54 95 57 74 24 73 16  3 84 83 86 16 18 51 55 80
 15 44 81 81 25 28 11 25 52 61 94 36 84 68 75 39 91 62 84 56 49 19 28 93
 97 87 49  9]
O numero que mais se repete: 9


In [154]:
# 12. Crie uma matriz 4x4 e substitua os valores da diagonal principal por 7.
matriz_4x4 = np.random.randint(1, 60, (3, 3))
print(f'Matriz original:\n{matriz_4x4}')
np.fill_diagonal(matriz_4x4, [7])
print(f'Matriz mudada:\n {matriz_4x4}')

Matriz original:
[[12 46 25]
 [47 10 51]
 [48  2 45]]
Matriz mudada:
 [[ 7 46 25]
 [47  7 51]
 [48  2  7]]


In [155]:
# 13. Crie um array contendo os 10 primeiros números pares e calcule sua soma cumulativa.
array_pares = np.arange(2, 21, 2)
print(f'Pares: {array_pares}')

somas = np.cumsum(array_pares)
print(somas)

Pares: [ 2  4  6  8 10 12 14 16 18 20]
[  2   6  12  20  30  42  56  72  90 110]


In [156]:
# 14. Calcule a diferença entre dois arrays de números aleatórios de mesmo comprimento e encontre a média das diferenças.
arrayePrimario = np.random.randint(1, 30, 20)
arrayeSecundario = np.random.randint(1, 30, 20)
print(f'Array1: {arrayePrimario}')
print(f'Array2: {arrayeSecundario}')
diferenca = arrayePrimario - arrayeSecundario
media = diferenca.mean()
print(f'Media das diferencas: {media}')


Array1: [ 2  5  4  1  6 28 16  5 26 24 17 10 13 20  3  8  4 25 22 11]
Array2: [ 4 13 11  5  7 24  1  3 13 17 25 16 23 11  1 11 21 26 10  3]
Media das diferencas: 0.25


In [157]:
# 15. Gere um array contendo 20 números e substitua todos os valores maiores que 50 por 50.
array_limitado = np.random.randint(1, 200, 20)
print(f'Array1: {array_limitado}')
array_limitado[array_limitado > 50] = 50
print(f'Array atualizado: {array_limitado}')

Array1: [112 162 137  46  59  23 187 139 159  36  94  90   3  68 133 187  17  59
  82 146]
Array atualizado: [50 50 50 46 50 23 50 50 50 36 50 50  3 50 50 50 17 50 50 50]


In [166]:
# 16. Crie um array unidimensional e reorganize seus valores em uma matriz 3x4.
array_unidimensional = np.random.randint(1, 20, 12)
print(f'Array1: {array_unidimensional}')
matriz_nova = array_unidimensional.reshape(3,4)
print(matriz_nova)

Array1: [16 12 17  8 13  9  1 13  5 10  8  3]
[[16 12 17  8]
 [13  9  1 13]
 [ 5 10  8  3]]


In [173]:
# 17. Gere uma matriz 4x4 de números inteiros aleatórios e multiplique cada valor por sua posição na matriz.
matriz_4x4 = np.random.randint(1, 10, (4, 4))
print(f'Matriz:\n{matriz_4x4}')
matriz_zerada = np.arange(0,16).reshape(4, 4)
print(f'Matriz:\n{matriz_zerada}')

multMatriz = matriz_4x4 * matriz_zerada
print(f'Matriz multiplicada:\n{multMatriz}')

Matriz:
[[8 4 5 4]
 [4 8 3 9]
 [8 5 4 9]
 [2 1 8 2]]
Matriz:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Matriz multiplicada:
[[  0   4  10  12]
 [ 16  40  18  63]
 [ 64  45  40  99]
 [ 24  13 112  30]]


In [178]:
# 18. Crie um array de 10 elementos contendo números entre 1 e 100 e substitua todos os valores múltiplos de 5 por 0.
array_10elementos = np.random.randint(1, 101, 10)
print(f'Array:\n{array_10elementos}')
array_10elementos[array_10elementos % 5 == 0] = 0
print(f'Array multiplos de 5 retirado:\n{array_10elementos}')

Array:
[18  2 46 41 47 29 16 57 77 70]
Array multiplos de 5 retirado:
[18  2 46 41 47 29 16 57 77  0]


In [182]:
# 19. Crie dois arrays de números inteiros aleatórios de tamanho 20 e calcule o ângulo entre eles (produto escalar normalizado).
array_pri = np.random.randint(1, 101, 20)
array_sec = np.random.randint(1, 101, 20)
produto_escalar = np.dot(array_pri,array_sec )

vetor1 = np.linalg.norm(array_pri)
vetor2 = np.linalg.norm(array_sec)
cosseno = produto_escalar / (vetor1 * vetor2)

angulo = np.arccos(cosseno)
print(f'array_pri {array_pri}')
print(f'array_sec {array_sec}')
print(f'Cosseno: {cosseno}')
print(f'Angulo: {angulo}')
print(f'Ângulo em graus: {np.degrees(angulo)}')


array_pri [ 57  70  72  23  85  11  60  54   9   1  83  32  30 100  66  24  56  43
  90  51]
array_sec [  2  10  42  90   3   7  54  16 100  41   3  19  23  30  68  47  28   6
  90  95]
Cosseno: 0.6157639792839987
Angulo: 0.9074411250358321
Ângulo em graus: 51.9925466211564


In [189]:
# 20. Crie uma matriz de números inteiros e encontre o valor mínimo de cada linha.
matriz_4x4 = np.random.randint(1, 40, (4, 4))
print(f'Matriz \n{matriz_4x4}')

menores = matriz_4x4.min(axis = 1)
print(f'Menor valor de cada linha \n{menores}')

Matriz 
[[28 36  5  2]
 [26  4 31 13]
 [17 38 19 18]
 [10 20 10 36]]
Menor valor de cada linha 
[ 2  4 17 10]
