<a href="https://colab.research.google.com/github/httpMatheus-dev/inteligencia-artificial-umc/blob/main/Exerc%C3%ADcios_DataScience_MatheusGabriel_6B_Noturno.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercícios de NumPy, SciPy, Pandas e Matplotlib — Lista 2

**Aluno:** Matheus Gabriel Alves da Silva | **RGM:** 11241100109  
**Turma:** 6B — Noturno | **Disciplina:** Inteligência Artificial — UMC  
**Professor:** Dr. Fabiano B. Menegidio


---
# 1. NumPy

In [25]:
import numpy as np

In [ ]:
# 1. Crie um array unidimensional de 50 elementos contendo numeros inteiros aleatorios entre 10 e 100.

listaArray = np.random.randint(10, 101, 50)

print(listaArray)


[55 69 15 40 12 96 55 68 50 96 19 36 88 45 65 64 50 61 26 34 69 95 99 99
 58 20 18 45 74 15 31 52 56 83 44 52 81 59 53 48 71 15 61 13 43 78 24 11
 68 45]


In [ ]:
# 2. Gere uma matriz 4x4 com numeros inteiros de 1 a 16 e extraia a ultima linha.

matriz_4x4 = np.arange(1, 17).reshape(4, 4)
ultima_linha = matriz_4x4[-1]

print(matriz_4x4)
print()
print(ultima_linha)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[13 14 15 16]


In [ ]:
# 3. Crie um array de zeros com comprimento 15 e substitua os valores da 5ª a 10ª posicao por 1.

array_zerado = np.zeros(15)
print(f'Array criado e zerado: {array_zerado}')

array_zerado[4:10] = 1
print(f'Array com o 1: {array_zerado}')


Array criado e zerado: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array com o 1: [0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


In [ ]:
# 4. Gere um array de 100 numeros inteiros aleatorios e encontre a mediana e a moda dos valores.

arrayInteiros = np.random.randint(1, 80, 100)
print(arrayInteiros)
mediana = np.median(arrayInteiros)
print(f'Mediana: {mediana}')
moda = np.argmax(np.bincount(arrayInteiros))
print(f'Moda: {moda}')

[46  4 27 50  4 11 31 19  9 54 51 76 51 77 74 39 47 73 40 20  1 21 72 37
 17 11 56 43 56  1 22 48 53 51 51 23 53 70 48 59 63 78 25 38 38 33 39 58
 47  6 14 16 22 34 37 46 61 37 14 72 51 50 38 32 69 54 75 66 60 59 30 36
 71 50 68 33 31 27 73 54 12 66 52 65 14 59 25 11 32 66 38 34 22 67 12  5
 67 17 20 34]
Mediana: 39.5
Moda: 51


In [ ]:
# 5. Crie um array de 20 elementos contendo numeros entre 1 e 100 e substitua todos os valores multiplos de 3 por -3.
arrayelementos = np.random.randint(1, 101, 20)
print(f'Array antes de mudar: {arrayelementos}')
arrayelementos[arrayelementos % 3 == 0] = -3
print()
print(f'Array apos mudar: {arrayelementos}')



Array antes de mudar: [95 29  3 54 29 41 85 99 20 58 89 51 63 15 29 99 30 68 89 19]

Array apos mudar: [95 29 -3 -3 29 41 85 -3 20 58 89 -3 -3 -3 29 -3 -3 68 89 19]


In [ ]:
# 6. Gere uma matriz 5x5 de numeros aleatorios entre 0 e 1 e encontre a soma de cada coluna.
matriz_5x5 = np.random.rand(5,5)
print(f'Matriz:\n{matriz_5x5}')

somaColunas = matriz_5x5.sum(axis=0)
print(f'Soma das colunas: {somaColunas}')

Matriz:
[[0.2774233  0.81397898 0.59941226 0.39837574 0.28753213]
 [0.0105974  0.92870887 0.9707378  0.38574362 0.96111611]
 [0.44398397 0.17358377 0.53178189 0.94856979 0.85926249]
 [0.51421706 0.39637895 0.31936886 0.05158228 0.54454657]
 [0.12278282 0.22019183 0.71381177 0.71452238 0.65871083]]
Soma das colunas: [1.36900454 2.5328424  3.13511257 2.49879381 3.31116812]


In [ ]:
# 7. Crie dois arrays de numeros aleatorios e encontre a correlacao entre eles
arrayePrimario = np.random.randint(1, 30, 20)
arrayeSecundario = np.random.randint(1, 30, 20)
correlacao = np.corrcoef(arrayePrimario, arrayeSecundario) [0, 1]

print(f'Primeiro: {arrayePrimario}')
print(f'Secundario: {arrayeSecundario}')
print(f'Correlacao: {correlacao}')

Primeiro: [25 28 11 25  5 15 18  5 13  3 23 21  2 25 23  2  5  6 22 10]
Secundario: [ 2  3 19  1 13 16  1  1 17  8 19  8 16 13  6 16 16 22 20 20]
Correlacao: -0.37211310390061275


In [ ]:
# 8. Gere uma matriz 3x3 com numeros inteiros aleatorios e eleve todos os seus elementos ao quadrado.

matriz_3x3 = np.random.randint(1, 10, (3, 3))
print(f'Matriz:\n{matriz_3x3}')
elevados = matriz_3x3 ** 2
print(f'Quadrados:\n{elevados}')


Matriz:
[[5 1 1]
 [7 9 2]
 [7 4 1]]
Quadrados:
[[25  1  1]
 [49 81  4]
 [49 16  1]]


In [ ]:
# 9. Crie um array com 10 numeros aleatorios e normalize seus valores entre 0 e 1
array_10 = np.random.randint(1, 20, 10)
print(array_10)

normalizado = (array_10 - array_10.min()) / (array_10.max() - array_10.min())
print(normalizado)

print(normalizado.min())   # tem que dar 0.0
print(normalizado.max())   # tem que dar 1.0

[ 5  4  9  7  4 13 19  9 18 15]
[0.06666667 0.         0.33333333 0.2        0.         0.6
 1.         0.33333333 0.93333333 0.73333333]
0.0
1.0


In [ ]:
# 10. Crie uma matriz identidade 6x6 e substitua a diagonal principal por valores crescentes de 1 a 6.
matriz_6x6 = np.eye(6)
print(matriz_6x6)
np.fill_diagonal(matriz_6x6, [1,2,3,4,5,6])
print(matriz_6x6)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 6.]]


In [ ]:
# 11. Gere um array de 100 números inteiros e encontre o valor que mais se repete no array.
array_100 = np.random.randint(1, 100, 100)
print((f'array original:\n{array_100}'))
repete = np.argmax(np.bincount(array_100))
print(f'O numero que mais se repete: {repete}')

# bincount conta quantas vezes cada número aparece;
# o índice do resultado é o próprio número, então argmax devolve a moda

array original:
[10 37 84  2 16 20 11 62 14 61 49 11 75 82 10 55 20 38  8 12 20 11 56  9
 36  7 57 94 30 69 44 94 89 34 37 66 78 58  9 93 55 91 53 56 57 95  4  9
 55  1 70 28 41 10  7  7 54 95 57 74 24 73 16  3 84 83 86 16 18 51 55 80
 15 44 81 81 25 28 11 25 52 61 94 36 84 68 75 39 91 62 84 56 49 19 28 93
 97 87 49  9]
O numero que mais se repete: 9


In [ ]:
# 12. Crie uma matriz 4x4 e substitua os valores da diagonal principal por 7.
matriz_4x4 = np.random.randint(1, 60, (3, 3))
print(f'Matriz original:\n{matriz_4x4}')
np.fill_diagonal(matriz_4x4, [7])
print(f'Matriz mudada:\n {matriz_4x4}')

Matriz original:
[[12 46 25]
 [47 10 51]
 [48  2 45]]
Matriz mudada:
 [[ 7 46 25]
 [47  7 51]
 [48  2  7]]


In [ ]:
# 13. Crie um array contendo os 10 primeiros números pares e calcule sua soma cumulativa.
array_pares = np.arange(2, 21, 2)
print(f'Pares: {array_pares}')

somas = np.cumsum(array_pares)
print(somas)

Pares: [ 2  4  6  8 10 12 14 16 18 20]
[  2   6  12  20  30  42  56  72  90 110]


In [ ]:
# 14. Calcule a diferença entre dois arrays de números aleatórios de mesmo comprimento e encontre a média das diferenças.
arrayePrimario = np.random.randint(1, 30, 20)
arrayeSecundario = np.random.randint(1, 30, 20)
print(f'Array1: {arrayePrimario}')
print(f'Array2: {arrayeSecundario}')
diferenca = arrayePrimario - arrayeSecundario
media = diferenca.mean()
print(f'Media das diferencas: {media}')


Array1: [ 2  5  4  1  6 28 16  5 26 24 17 10 13 20  3  8  4 25 22 11]
Array2: [ 4 13 11  5  7 24  1  3 13 17 25 16 23 11  1 11 21 26 10  3]
Media das diferencas: 0.25


In [ ]:
# 15. Gere um array contendo 20 números e substitua todos os valores maiores que 50 por 50.
array_limitado = np.random.randint(1, 200, 20)
print(f'Array1: {array_limitado}')
array_limitado[array_limitado > 50] = 50
print(f'Array atualizado: {array_limitado}')

Array1: [112 162 137  46  59  23 187 139 159  36  94  90   3  68 133 187  17  59
  82 146]
Array atualizado: [50 50 50 46 50 23 50 50 50 36 50 50  3 50 50 50 17 50 50 50]


In [ ]:
# 16. Crie um array unidimensional e reorganize seus valores em uma matriz 3x4.
array_unidimensional = np.random.randint(1, 20, 12)
print(f'Array1: {array_unidimensional}')
matriz_nova = array_unidimensional.reshape(3,4)
print(matriz_nova)

Array1: [16 12 17  8 13  9  1 13  5 10  8  3]
[[16 12 17  8]
 [13  9  1 13]
 [ 5 10  8  3]]


In [ ]:
# 17. Gere uma matriz 4x4 de números inteiros aleatórios e multiplique cada valor por sua posição na matriz.
matriz_4x4 = np.random.randint(1, 10, (4, 4))
print(f'Matriz:\n{matriz_4x4}')
matriz_zerada = np.arange(0,16).reshape(4, 4)
print(f'Matriz:\n{matriz_zerada}')

multMatriz = matriz_4x4 * matriz_zerada
print(f'Matriz multiplicada:\n{multMatriz}')

Matriz:
[[8 4 5 4]
 [4 8 3 9]
 [8 5 4 9]
 [2 1 8 2]]
Matriz:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Matriz multiplicada:
[[  0   4  10  12]
 [ 16  40  18  63]
 [ 64  45  40  99]
 [ 24  13 112  30]]


In [ ]:
# 18. Crie um array de 10 elementos contendo números entre 1 e 100 e substitua todos os valores múltiplos de 5 por 0.
array_10elementos = np.random.randint(1, 101, 10)
print(f'Array:\n{array_10elementos}')
array_10elementos[array_10elementos % 5 == 0] = 0
print(f'Array multiplos de 5 retirado:\n{array_10elementos}')

Array:
[18  2 46 41 47 29 16 57 77 70]
Array multiplos de 5 retirado:
[18  2 46 41 47 29 16 57 77  0]


In [ ]:
# 19. Crie dois arrays de números inteiros aleatórios de tamanho 20 e calcule o ângulo entre eles (produto escalar normalizado).
array_pri = np.random.randint(1, 101, 20)
array_sec = np.random.randint(1, 101, 20)
produto_escalar = np.dot(array_pri,array_sec )

vetor1 = np.linalg.norm(array_pri)
vetor2 = np.linalg.norm(array_sec)
cosseno = produto_escalar / (vetor1 * vetor2)

angulo = np.arccos(cosseno)
print(f'array_pri {array_pri}')
print(f'array_sec {array_sec}')
print(f'Cosseno: {cosseno}')
print(f'Angulo: {angulo}')
print(f'Ângulo em graus: {np.degrees(angulo)}')


array_pri [ 57  70  72  23  85  11  60  54   9   1  83  32  30 100  66  24  56  43
  90  51]
array_sec [  2  10  42  90   3   7  54  16 100  41   3  19  23  30  68  47  28   6
  90  95]
Cosseno: 0.6157639792839987
Angulo: 0.9074411250358321
Ângulo em graus: 51.9925466211564


In [ ]:
# 20. Crie uma matriz de números inteiros e encontre o valor mínimo de cada linha.
matriz_4x4 = np.random.randint(1, 40, (4, 4))
print(f'Matriz \n{matriz_4x4}')

menores = matriz_4x4.min(axis = 1)
print(f'Menor valor de cada linha \n{menores}')

Matriz 
[[28 36  5  2]
 [26  4 31 13]
 [17 38 19 18]
 [10 20 10 36]]
Menor valor de cada linha 
[ 2  4 17 10]


---
# 2. SciPy


In [4]:
# 1. Calcule a integral da função f(x) = x² * sin(x)
#    no intervalo de 0 a π.

from scipy import integrate
def f(x):
  return x**2 * np.sin(x)

resultado, erro = integrate.quad(f, 0, np.pi)
print('Resultado da integral: ', resultado)
print('Erro estimado: ', erro)

Resultado da integral:  5.869604401089359
Erro estimado:  6.516569951530559e-14


In [8]:
# 2. Resolva a equação diferencial:
#    dy/dx = x - y
#    com y(0) = 1, no intervalo de 0 a 10.

from scipy.integrate import solve_ivp
def eqDif(x, y):
    return x - y

sol = solve_ivp(eqDif, [0, 10], [1], t_eval=np.linspace(0, 10, 100))

print(f'Tempos: {sol.t}')
print(f'Solução y: {sol.y[0]}')

Tempos: [ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.181

In [17]:
# 3. Encontre as raízes da função:
#    f(x) = x⁴ - 3x³ + 2
#    utilizando SciPy.

from scipy.optimize import root

def f(x):
  return x**4 - 3*x**3 + 2

# Verificação dos valores da função para identificar possíveis trocas de sinal.
for x in [-2, -1, 0, 1, 2, 3, 4]:
    print(f'x = {x}: f(x) = {f(x)}')

r1 = root(f, 1)
r2 = root(f, 2.5)

print(f'Raiz 1: {r1.x}')
print(f'Raiz 2: {r2.x}')


x = -2: f(x) = 42
x = -1: f(x) = 6
x = 0: f(x) = 2
x = 1: f(x) = 0
x = 2: f(x) = -6
x = 3: f(x) = 2
x = 4: f(x) = 66
Raiz 1: [1.]
Raiz 2: [2.91963957]


In [21]:
# 4. Use a função de otimização do SciPy para maximizar:
#    f(x) = -x² + 4x + 1.
from scipy.optimize import minimize


def f_maximizar(x):
    return -(-x**2 + 4*x + 1)
resultado = minimize(f_maximizar, 0)
print(f'Máximo em x = {resultado.x}')
print(f'Valor máximo = {-resultado.fun}')

Máximo em x = [2.00000003]
Valor máximo = 4.999999999999999


In [78]:
# 5. Calcule a Transformada de Fourier de um sinal composto por:
#    sin(2πt) + cos(4πt).
from scipy.fft import fft
t = np . linspace (0, 1, 500)
sinal = np.sin (2 * np.pi * t) + np.cos (4 * np.pi * t)
frequencias = fft ( sinal )
print(np.abs(frequencias[:10]))

[1.00000000e+00 2.49751643e+02 2.50244558e+02 8.89142336e-01
 4.28635937e-01 2.83233950e-01 2.12801777e-01 1.71273967e-01
 1.43818423e-01 1.24257994e-01]


In [76]:
# 6. Encontre a matriz inversa de uma matriz 5x5
#    de números aleatórios.
from scipy.linalg import inv


matriz_5x5 = np.random.rand(5,5)
inversa = inv(matriz_5x5)

print(f'Matriz:\n{matriz_5x5}')
print(f'Inversa:\n{inversa}')
print(f'Verificação (matriz × inversa):\n{np.dot(matriz_5x5, inversa)}')

Matriz:
[[0.87649052 0.56558214 0.98851075 0.56819201 0.02394581]
 [0.42168421 0.84814296 0.42388364 0.63933086 0.97058937]
 [0.06180091 0.72271966 0.06552701 0.26813198 0.55525951]
 [0.62347267 0.39731458 0.36443294 0.39634819 0.12707034]
 [0.76981013 0.6686018  0.83853862 0.87291463 0.36934252]]
Inversa:
[[-0.00729624  1.02101213 -1.31309424  3.35297614 -1.86213214]
 [ 0.55691051 -1.6346203   2.8839543   0.22746394 -0.15442996]
 [ 2.26144141  0.95102611 -0.67838255 -3.03820911 -0.58066221]
 [-2.73128929 -1.71754249  0.41631677 -0.10196881  4.09978464]
 [ 0.327993    2.73112462 -1.92759512 -0.2614701  -1.50297879]]
Verificação (matriz × inversa):
[[ 1.00000000e+00 -2.27566545e-16  1.04653212e-16 -2.71037982e-16
   7.78885463e-17]
 [ 1.63568707e-16  1.00000000e+00  5.52629597e-17  1.24525620e-16
   3.39909152e-17]
 [-4.70778764e-17 -1.91863769e-16  1.00000000e+00 -2.38245196e-17
   8.60649815e-17]
 [-5.60123629e-17 -1.44810881e-16  1.83208316e-17  1.00000000e+00
   6.33237311e-18]
 [ 3

In [65]:
# 7. Use a interpolação cúbica do SciPy para interpolar
#    os pontos:
#    (0,0), (1,2), (2,3), (3,5), (4,4).
from scipy import interpolate
 # Definir os pontos
x = np.array ([0 , 1, 2 , 3 , 4])
y = np.array ([0 , 2, 3 , 5 , 4])

# Criar a fun o de interpolacao
f_interpolada = interpolate . interp1d (x, y, kind='cubic')

x_novos = np.array([0.5, 1.5, 2.5, 3.5])
y_novos = f_interpolada(x_novos)
print("Valores interpolados :", x_novos, y_novos )


Valores interpolados : [0.5 1.5 2.5 3.5] [1.34375 2.40625 4.03125 5.21875]


In [36]:
# 8. Resolva o sistema de equações:
#  3x + 2y = 5
#  x + 4y = 6

from scipy import linalg

A = np.array([[3, 2], [1, 4]])
B = np.array([5,6])

solucao = linalg.solve(A, B)

print(solucao)

[0.8 1.3]


In [38]:
# 9. Ajuste uma curva quadrática aos pontos:
#    (1,2), (2,4), (3,5), (4,7), (5,8).
from scipy.optimize import curve_fit

def parabola(x, a, b, c):
    return a * x**2 + b * x + c

x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 5, 7, 8])

parametros, _ = curve_fit(parabola, x, y)

print(f'Parâmetros [a, b, c]: {parametros}')

Parâmetros [a, b, c]: [-0.07142857  1.92857143  0.2       ]


In [39]:
# 10. Calcule a integral dupla da função:
#     f(x, y) = xy + x²
#     com:
#     x ∈ [0, 2]
#     y ∈ [0, 1].

from scipy.integrate import dblquad

def f(y, x):
    return x*y + x**2

resultado, erro = dblquad(f, 0, 2, 0, 1)
print(resultado)

3.666666666666667


In [42]:
# 11. Encontre os autovalores e autovetores
#     de uma matriz 4x4 de números inteiros aleatórios.
from scipy import linalg
matriz_4x4 = np.random.randint(1, 40, (4, 4))

autovalores, autovetores = linalg.eig(matriz_4x4)

print(f'Autovalores:\n{autovalores}')
print(f'Autovetores:\n{autovetores}')

Autovalores:
[ 93.54498002+0.j         -15.39286968+0.j
   2.92394483+2.52018166j   2.92394483-2.52018166j]
Autovetores:
[[-0.49792654+0.j         -0.06833072+0.j         -0.54989231-0.04513015j
  -0.54989231+0.04513015j]
 [-0.40761967+0.j          0.57893635+0.j         -0.35851553+0.12788266j
  -0.35851553-0.12788266j]
 [-0.63581654+0.j         -0.65359025+0.j          0.34766436-0.05150798j
   0.34766436+0.05150798j]
 [-0.42620733+0.j          0.48268355+0.j          0.65358304+0.j
   0.65358304-0.j        ]]
83.99999999999986
84


In [43]:
# 12. Resolva a equação:
#     e^x - x² = 0
#     encontrando a raiz mais próxima de x = 1.

from scipy.optimize import fsolve

def f(x):
    return np.exp(x) - x**2

raiz = fsolve(f, 1)
print(f'Raiz: {raiz}')

Raiz: [-0.70346742]


In [44]:
# 13. Calcule o determinante de uma matriz 6x6
#     de números aleatórios entre -10 e 10.

from scipy import linalg

matriz_6x6 = np.random.randint(-10, 11, (6, 6))
determinante = linalg.det(matriz_6x6)

print(f'Matriz:\n{matriz_6x6}')
print(f'Determinante: {determinante}')

Matriz:
[[  3  -4  -3  -3  -1   9]
 [  4   7  -7   7   8 -10]
 [ -2   3  -2   8  -7   8]
 [ -9  -7   4  -4   7   7]
 [ -5   3   8   0  -2  10]
 [  1   9  -7  -1   0 -10]]
Determinante: 1695650.0


In [45]:
# 14. Utilize a otimização multivariada para minimizar:
#     f(x, y) = (x - 2)² + (y - 3)².

def f(v):
    x, y = v
    return (x - 2)**2 + (y - 3)**2

minimize(f, [0, 0])

resultado = minimize(f, [0, 0])
print(f'Mínimo em [x, y] = {resultado.x}')

Mínimo em [x, y] = [1.99999999 2.99999999]


In [48]:
# 15. Calcule a Transformada de Fourier Inversa
#     de um sinal complexo gerado aleatoriamente.

from scipy.fft import ifft
sinal_complexo = np.random.rand(50) + 1j * np.random.rand(50)

sinal_tempo = ifft(sinal_complexo)
print(np.allclose(fft(sinal_tempo), sinal_complexo))
print(f'Sinal complexo (5 primeiros):\n{sinal_complexo[:5]}')
print(f'Após ifft (5 primeiros):\n{sinal_tempo[:5]}')

True
Sinal complexo (5 primeiros):
[0.14427579+0.38799892j 0.70372582+0.06404044j 0.20120149+0.90583741j
 0.89997236+0.27910168j 0.98491449+0.19014961j]
Após ifft (5 primeiros):
[ 0.55561647+0.51424894j -0.01251139+0.06791778j  0.06176139+0.01187808j
  0.00817472-0.04062225j  0.02284956+0.02373768j]


In [56]:
# 16. Resolva a equação diferencial de segunda ordem:
#     d²y/dx² + y = 0
#     com:
#     y(0) = 1
#     y'(0) = 0.

def eq(x, y):
    return [y[1], -y[0]]
sol = solve_ivp(eq, [0, 10], [1, 0], t_eval=np.linspace(0, 10, 100), rtol=1e-8, atol=1e-10)
print(f'Solução bate com cos(x): {np.allclose(sol.y[0], np.cos(sol.t))}')
print(f'Solução y (10 primeiros): {sol.y[0][:10]}')


Solução bate com cos(x): True
Solução y (10 primeiros): [1.         0.99490282 0.97966323 0.95443659 0.91948007 0.87515004
 0.8218984  0.76026803 0.69088721 0.61446322]


In [63]:
# 17. Encontre a raiz cúbica de 27
#     utilizando SciPy.

from scipy.optimize import fsolve

def f(x):
    return x**3 - 27

raiz = fsolve(f, 2)
print(f'Raiz cúbica de 27: {raiz}')

Raiz cúbica de 27: [3.]


In [66]:
# 18. Interpole a função:
#     f(x) = x²
#     nos pontos [1, 2, 3, 4, 5]
#     utilizando spline cúbica.

from scipy.interpolate import interp1d

x = np.array([1, 2, 3, 4, 5])
y = x **2

f_spline = interp1d(x, y, kind='cubic')

x_novos = np.array([1.5, 2.5, 3.5, 4.5])
y_novos = f_spline(x_novos)

print(f'Pontos originais: {y}')
print(f'Valores interpolados: {y_novos}')

Pontos originais: [ 1  4  9 16 25]
Valores interpolados: [ 2.25  6.25 12.25 20.25]


In [74]:
# 19. Realize a Transformada de Fourier
#     de um sinal discreto composto por senos e cossenos.

t = np.linspace(0, 1, 500)
onda_cos = np.cos(10 * np.pi * t)
onda_sin = np.sin(6 * np.pi * t)
sinal = onda_cos + onda_sin

frequencias = fft(sinal)

print(f'Magnitudes (10 primeiras): {np.abs(frequencias[:10])}')

Magnitudes (10 primeiras): [  1.           1.10661003   1.68518835 249.73970722   3.25378817
 250.21085936   2.39752054   1.17457493   0.77945491   0.58553862]


In [73]:
# 20. Resolva um sistema de equações lineares
#     com três variáveis utilizando SciPy.
# x -  y + 2z = 8
# 2x + 3y -  z = 1
# -x + 2y + 4z = 3

A = np.array([[1,  -1,  2],
              [2, 3, -1],
              [-1,  2, 4]])
B = np.array([8, 1, 3])

solucao = linalg.solve(A, B)
print(f'Solução [x, y, z]: {solucao}')

Solução [x, y, z]: [ 3. -1.  2.]
